### ISSUE TITLE
Picture of EV3

### ISSUE THREAD

**Issue by aizu-wakamatsu** [rem-s/rem-s.github.io#2]
I thought it is necessary to write some description of EV3 picture at the top of this website.

**Comment by gpioblink** [comment]
@aizu-wakamatsu いいですね！書いてください。僕は参加していないのでわかりません

**Comment by aizu-wakamatsu** [comment]
@gpioblinc OK. I will write description in few days.

**Comment by gpioblink** [comment]
@aizu-wakamatsu 進捗どうですか？

**Comment by aizu-wakamatsu** [comment]
HOME MADE SHINCHOKU

**Comment by gpioblink** [comment]
@aizu-wakamatsu 進展ないようならクローズします
